print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("________________________HOODSENSE.CC__________________________")
print("| [hoodsense.cc] Re-Whitelist in progress.                   |")
print("| [hoodsense.cc] Your HWID is:                               |")
print(game:GetService("RbxAnalyticsService"):GetClientId())    
print("| [hoodsense.cc] HWID copied on clipboard.                   |")
setclipboard(game:GetService("RbxAnalyticsService"):GetClientId())
print("| [hoodsense.cc] Succesfully logged your HWID.               |")
print("| [hoodsense.cc] Create ticket or vist #re-whitelist channel |")
print("______________________________________________________________")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
